### PR TITLE
pgmq-rs - Leverage parametrized queries from core

### LINKED ISSUE #185: pgmq-rs can't save strings with apostrophe in them
Hey guys!

This is a great crate, thanks so much!

I'm trying to use it to encode a message, which is a string we get from the user, and apparently if that string includes an apostrophe it fails to save because, well, the lib doesn't escape it. Example:
let's say I want to write the following JSON message:
```json
{
     "to-do": "don't delete before you read it"
}
```

Then, when I try to save it, it turns into the following query:
```sql
INSERT INTO pgmq.q_github_events_jobs (vt, message)
VALUES ((now() + interval '0 seconds'), '{
    "to-do": "don't delete before you read it"
}'::json)
	        RETURNING msg_id;
```

Which even this preview shows is broken. Need to escape the `'` characters by duplicating them, i.e. this would work:
```sql
INSERT INTO pgmq.q_github_events_jobs (vt, message)
VALUES ((now() + interval '0 seconds'), '{
    "to-do": "don''t delete before you read it"
}'::json)
	        RETURNING msg_id;
```

Are you guys open for a contribution? Any specific pointers?

### PR DESCRIPTION
**Pull request by nimrodkor**
Part 2 of 2. Makes pgmq-rs leverage the parametrized methods in the new core version that will be published.

Will break UTs until the new version is published

Depends on #186 . Resolves #185

### CODE REVIEW

File: pgmq-rs/src/lib.rs [hunk 1]
```diff
@@ -440,15 +439,12 @@ impl PGMQueue {
         queue_name: &str,
         messages: &[T],
     ) -> Result<Vec<i64>, PgmqError> {
-        let mut msgs: Vec<serde_json::Value> = Vec::new();
         let mut msg_ids: Vec<i64> = Vec::new();
+        let mut q = sqlx::query(&core_query::enqueue(queue_name, messages.len(), &0)?);
```
Comment (ChuckHend) [inline pgmq-rs/src/lib.rs:443]: might have to move `core_query::enqueue(queue_name, messages.len(), &0)` into its own let statement to resolve:

```
   --> src/lib.rs:443:34
    |
443 |         let mut q = sqlx::query(&core_query::enqueue(queue_name, messages.len(), &0)?);
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ - temporary value is freed at the end of this statement
    |                                  |
    |                                  creates a temporary value which is freed while still in use

```

Comment (ChuckHend) [reply pgmq-rs/src/lib.rs]: I pushed a change up for this. Turns out that change we merged in `pgmq-core` was breaking, so we need to get this pushed out now to resolve it. I should have caught that before, maybe we can get a test in place for it.

**Review by ChuckHend — APPROVED** [review]
Thank you for the contributions!
